/*
 * generated by Xtext 2.22.0
 */
package org.palladiosimulator.dataflow.dictionary.characterized.behavior.dsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.palladiosimulator.dataflow.dictionary.characterized.DataDictionaryCharacterized.BehaviorDefinition

@ExtendWith(InjectionExtension)
@InjectWith(BehaviorDefinitionInjectorProvider)
class BehaviorDefinitionParsingTest {
	@Inject
	ParseHelper<BehaviorDefinition> parseHelper
	
	@Test
	def testEmptyBehavior() {
		assertNoErrorInParsing('''
		behavior "test"
		''')
	}
	
	def protected void assertNoErrorInParsing(String text) {
		val result = parseHelper.parse(text)
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
