<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DataFlowDiagramCharacterized" nsURI="http://palladiosimulator.org/dataflow/diagram/characterized/1.0"
    nsPrefix="DataFlowDiagramCharacterized">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Characterizable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="characteristics" upperBound="-1"
        eType="ecore:EClass ../../org.palladiosimulator.dataflow.dictionary.characterized/model/DataDictionaryCharacterized.ecore#//Characteristic"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="derivation" value="self.ownedCharacteristics->union(referencedCharacteristics)->selectByKind(DataDictionaryCharacterized::Characteristic)->sortedBy(id)->asOrderedSet()"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedCharacteristics" upperBound="-1"
        eType="ecore:EClass ../../org.palladiosimulator.dataflow.dictionary.characterized/model/DataDictionaryCharacterized.ecore#//Characteristic"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedCharacteristics"
        upperBound="-1" eType="ecore:EClass ../../org.palladiosimulator.dataflow.dictionary.characterized/model/DataDictionaryCharacterized.ecore#//Characteristic"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CharacterizedExternalActor" eSuperTypes="../../org.palladiosimulator.dataflow.diagram/model/DataFlowDiagram.ecore#//ExternalActor #//CharacterizedNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="CharacterizedStore" eSuperTypes="../../org.palladiosimulator.dataflow.diagram/model/DataFlowDiagram.ecore#//Store #//CharacterizedNode">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="storeHasNoAssignmentsInBehavior storeHasExactlyOneInputAndOneOutputPin"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="storeHasNoAssignmentsInBehavior" value="self.behavior.assignments->isEmpty()"/>
      <details key="storeHasExactlyOneInputAndOneOutputPin" value="self.behavior.inputs->size() = 1 and self.behavior.outputs->size() = 1"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CharacterizedProcess" eSuperTypes="../../org.palladiosimulator.dataflow.diagram/model/DataFlowDiagram.ecore#//Process #//CharacterizedNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="CharacterizedDataFlow" eSuperTypes="../../org.palladiosimulator.dataflow.diagram/model/DataFlowDiagram.ecore#//DataFlowEdge #//Characterizable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="sourcePinIsEntityOutputPin destinationPinIsEntityInputPin sourcePinOwnerMatchesSource destinationPinOwnerMatchesDestination notPartOfLoop"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="sourcePinIsEntityOutputPin" value="self.sourcePin.owner.outputs->includes(self.sourcePin)"/>
      <details key="destinationPinIsEntityInputPin" value="self.targetPin.owner.inputs->includes(self.targetPin)"/>
      <details key="sourcePinOwnerMatchesSource" value="not self.source.oclIsKindOf(Behaving) or self.source.oclAsType(Behaving).behavior.outputs->includes(self.sourcePin)"/>
      <details key="destinationPinOwnerMatchesDestination" value="not self.target.oclIsKindOf(Behaving) or self.target.oclAsType(Behaving).behavior.inputs->includes(self.targetPin)"/>
      <details key="notPartOfLoop" value="not self.oclAsType(DataFlowDiagram::Edge)->closure(e |&#xA;&#x9;self.oclAsType(ecore::EObject).eContainer().oclAsType(DataFlowDiagram::DataFlowDiagram).edges->select(f |&#xA;&#x9;&#x9;f.source = e.target and&#xA;&#x9;&#x9;not f.source->including(f.target)->exists(n | n.oclIsKindOf(CharacterizedExternalActor))&#xA;&#x9;)&#xA;)->exists(f | f.target = self.source)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePin" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.dataflow.dictionary.characterized/model/DataDictionaryCharacterized.ecore#//Pin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPin" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.dataflow.dictionary.characterized/model/DataDictionaryCharacterized.ecore#//Pin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CharacterizedActorProcess" eSuperTypes="#//CharacterizedProcess">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actor" lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.dataflow.diagram/model/DataFlowDiagram.ecore#//ExternalActor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CharacterizedNode" abstract="true" eSuperTypes="#//Characterizable #//Behaving">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="atLeastOneInputFlowForEachInputPin"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="atLeastOneInputFlowForEachInputPin" value="self.behavior.inputs->isEmpty() or CharacterizedDataFlow.allInstances()->select(f | f.target = self).targetPin->asSet()->includesAll(self.behavior.inputs->asSet())"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Behaving" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="exactlyOneBehaviorHasToBeSpecified"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="exactlyOneBehaviorHasToBeSpecified" value="self.ownedBehavior->including(self.referencedBehavior)->selectByKind(DataDictionaryCharacterized::BehaviorDefinition)->size() = 1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" lowerBound="1"
        eType="ecore:EClass ../../org.palladiosimulator.dataflow.dictionary.characterized/model/DataDictionaryCharacterized.ecore#//BehaviorDefinition"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="derivation" value="self.ownedBehavior->including(self.referencedBehavior)->selectByKind(DataDictionaryCharacterized::BehaviorDefinition)->any(true)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedBehavior" eType="ecore:EClass ../../org.palladiosimulator.dataflow.dictionary.characterized/model/DataDictionaryCharacterized.ecore#//BehaviorDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedBehavior" eType="ecore:EClass ../../org.palladiosimulator.dataflow.dictionary.characterized/model/DataDictionaryCharacterized.ecore#//BehaviorDefinition"/>
  </eClassifiers>
</ecore:EPackage>
