/*
 * generated by Xtext 2.22.0
 */
package org.palladiosimulator.dataflow.dictionary.characterized.behavior.dsl.ide;


/**
 * Use this class to register ide components.
 */
public class BehaviorDefinitionIdeModule extends AbstractBehaviorDefinitionIdeModule {
}
