/*
 * generated by Xtext 2.22.0
 */
package org.palladiosimulator.dataflow.dictionary.characterized.behavior.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.palladiosimulator.dataflow.dictionary.characterized.behavior.dsl.BehaviorDefinitionRuntimeModule;
import org.palladiosimulator.dataflow.dictionary.characterized.behavior.dsl.BehaviorDefinitionStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BehaviorDefinitionIdeSetup extends BehaviorDefinitionStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BehaviorDefinitionRuntimeModule(), new BehaviorDefinitionIdeModule()));
	}
	
}
