/*
 * generated by Xtext 2.23.0
 */
package org.palladiosimulator.dataflow.dictionary.characterized.dsl.scoping;

import java.util.ArrayList;
import java.util.Optional;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.naming.QualifiedName;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.resource.impl.AliasedEObjectDescription;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.impl.FilteringScope;
import org.palladiosimulator.dataflow.dictionary.characterized.DataDictionaryCharacterized.Assignment;
import org.palladiosimulator.dataflow.dictionary.characterized.DataDictionaryCharacterized.BehaviorDefinition;
import org.palladiosimulator.dataflow.dictionary.characterized.DataDictionaryCharacterized.expressions.CharacteristicReference;
import org.palladiosimulator.dataflow.dictionary.characterized.DataDictionaryCharacterized.expressions.DataCharacteristicReference;
import org.palladiosimulator.dataflow.dictionary.characterized.DataDictionaryCharacterized.expressions.ExpressionsPackage;
import org.palladiosimulator.dataflow.dictionary.characterized.DataDictionaryCharacterized.expressions.Term;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class CharacterizedDataDictionaryScopeProvider extends AbstractCharacterizedDataDictionaryScopeProvider {

    @Override
    public IScope getScope(EObject context, EReference reference) {
        var superScope = super.getScope(context, reference);
        if (reference == ExpressionsPackage.Literals.DATA_CHARACTERISTIC_REFERENCE__PIN) {
            var characteristicReference = Optional.ofNullable(context).filter(DataCharacteristicReference.class::isInstance).map(DataCharacteristicReference.class::cast);
            var behaviorDefinition = findParentOfType(context, BehaviorDefinition.class);
            var usablePins = new ArrayList<>();
            if (characteristicReference.map(this::isLhs).orElse(true)) {
                behaviorDefinition.map(BehaviorDefinition::getOutputs)
                .ifPresent(usablePins::addAll);
            }
            if (characteristicReference.map(this::isRhs).orElse(true)) {
                behaviorDefinition.map(BehaviorDefinition::getInputs)
                .ifPresent(usablePins::addAll);
            }
            return new FilteringScope(superScope, description -> usablePins.contains(description.getEObjectOrProxy()));
        }
        if (reference == ExpressionsPackage.Literals.ENUM_CHARACTERISTIC_REFERENCE__LITERAL) {
            return new TransformingScope(superScope, description -> Optional.ofNullable(description)
                .map(d -> (IEObjectDescription) new AliasedEObjectDescription(
                        QualifiedName.create(description.getQualifiedName()
                            .getLastSegment()),
                        d))
                .orElse(description));
        }
        return superScope;
    }

    @SuppressWarnings("unchecked")
    protected <T extends EObject> Optional<T> findParentOfType(EObject object, Class<T> parentType) {
        EObject currentObject = object;
        while (currentObject != null) {
            if (parentType.isInstance(currentObject)) {
                return Optional.of((T)currentObject);
            }
            currentObject = currentObject.eContainer();
        }
        return Optional.empty();
    }
    
    protected boolean isLhs(CharacteristicReference reference) {
        Optional<Assignment> assignment = findParentOfType(reference, Assignment.class);
        if (!assignment.isPresent()) {
            return false;
        }
        return assignment.get().getLhs() == reference;
    }

    protected boolean isRhs(CharacteristicReference reference) {
        Optional<Assignment> assignment = findParentOfType(reference, Assignment.class);
        if (!assignment.isPresent()) {
            return false;
        }
        
        Term rhsTerm = assignment.get().getRhs();
        if (rhsTerm == reference) {
            return true;
        }
        if (rhsTerm == null) {
            return false;
        }

        for (var iter = rhsTerm.eAllContents(); iter.hasNext();) {
            if (iter.next() == reference) {
                return true;
            }
        }
        
        return false;
    }
    
}
