/*
 * generated by Xtext 2.22.0
 */
package org.palladiosimulator.dataflow.dictionary.characterized.behavior.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BehaviorDefinitionUiModule extends AbstractBehaviorDefinitionUiModule {

	public BehaviorDefinitionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
