/*
 * generated by Xtext 2.23.0
 */
package org.palladiosimulator.dataflow.dictionary.characterized.dsl.ide;


/**
 * Use this class to register ide components.
 */
public class CharacterizedDataDictionaryIdeModule extends AbstractCharacterizedDataDictionaryIdeModule {
}
