/*
 * generated by Xtext 2.23.0
 */
package org.palladiosimulator.dataflow.dictionary.characterized.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.palladiosimulator.dataflow.dictionary.characterized.dsl.CharacterizedDataDictionaryRuntimeModule;
import org.palladiosimulator.dataflow.dictionary.characterized.dsl.CharacterizedDataDictionaryStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CharacterizedDataDictionaryIdeSetup extends CharacterizedDataDictionaryStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CharacterizedDataDictionaryRuntimeModule(), new CharacterizedDataDictionaryIdeModule()));
	}
	
}
