/*
 * generated by Xtext 2.23.0
 */
package org.palladiosimulator.dataflow.dictionary.characterized.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CharacterizedDataDictionaryUiModule extends AbstractCharacterizedDataDictionaryUiModule {

	public CharacterizedDataDictionaryUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
