/*
 * generated by Xtext 2.22.0
 */
package org.palladiosimulator.dataflow.dictionary.characterized.behavior.dsl.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class BehaviorDefinitionScopeProvider extends AbstractBehaviorDefinitionScopeProvider {

}
