/*
 * generated by Xtext 2.23.0
 */
package org.palladiosimulator.dataflow.dictionary.characterized.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CharacterizedDataDictionaryStandaloneSetup extends CharacterizedDataDictionaryStandaloneSetupGenerated {

	public static void doSetup() {
		new CharacterizedDataDictionaryStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
