/*
 * generated by Xtext 2.23.0
 */
package org.palladiosimulator.dataflow.dictionary.characterized.dsl;

import org.palladiosimulator.dataflow.dictionary.characterized.DataDictionaryCharacterized.DataDictionaryCharacterizedPackage;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CharacterizedDataDictionaryStandaloneSetup extends CharacterizedDataDictionaryStandaloneSetupGenerated {

	public static void doSetup() {
		new CharacterizedDataDictionaryStandaloneSetup().createInjectorAndDoEMFRegistration();
	}

    @Override
    public void register(Injector injector) {
        DataDictionaryCharacterizedPackage.eINSTANCE.eClass(); // register DDC package
        super.register(injector);
    }

}
